from django.contrib import admin
from NSLifecycleManagement.models import *
from django.apps import apps


admin.site.register(NsInstance)
admin.site.register(VnfInstance)
admin.site.register(VnffgInfo)
admin.site.register(SapInfo)
admin.site.register(NsMonitoringParame)
admin.site.register(NsScaleInfo)
admin.site.register(NsInstanceLinks)
admin.site.register(AffinityOrAntiAffinityRule)
admin.site.register(InstantiatedVnfInfo)
admin.site.register(VnfScaleInfo)
admin.site.register(VnfExtCpInfo)
admin.site.register(ExtLinkPortInfo)
admin.site.register(ExtManagedVirtualLinkInfo)
admin.site.register(ExtVirtualLinkInfo)
admin.site.register(VnfMonitoringParamet)
admin.site.register(VnfcResourceInfo)
admin.site.register(VnfcCpInfo)
admin.site.register(CpProtocolInfo)
admin.site.register(IpAddresses)
admin.site.register(IpOverEthernetAddressInfo)
admin.site.register(AddressRange)
admin.site.register(VnfVirtualLinkResourceInfo)
admin.site.register(VnfLinkPortInfo)
admin.site.register(VirtualStorageResourceInfo)
admin.site.register(NsVirtualLinkInfo)
admin.site.register(NsLinkPortInfo)
# admin.site.register(VnffgInfo)
admin.site.register(NfpInfo)
admin.site.register(NfpRule)
admin.site.register(CpGroupInfo)
admin.site.register(PortRange)
admin.site.register(Mask)
admin.site.register(CpPairInfo)
admin.site.register(ForwardingBehaviourInputParameters)
admin.site.register(NsCpHandle)
admin.site.register(ResourceHandle)